### ISSUE TITLE
VLC Parametresi Eksik

### ISSUE THREAD

**Issue by Aykut551** [DeoDorqnt387/aniwatch-tr#1]
VLC Parametresi Eksik.

**Comment by DeoDorqnt387** [comment]
Vlc parametresi eksik demek isterken mpv değilde vlc ile izlemek istediğini mi kastettin?
Eğer öyleyse onun için bir seçim veya bilgisayarda vlc varsa vlc'yi kullansın mpv varsa mpv'yi kullansın diye değiştirebilirim.
Şu anda sadece mpv ile çalışmakta.

**Comment by Aykut551** [comment]
Orijinal ani-cli komutunda -v parametresi eklendiğinde vlc üzerinden açar yoksa mpv üzerinden açar aynı konsept kullanılabilir

**Comment by DeoDorqnt387** [comment]
Şimdi yanlış anlaşılmayalım bu ani-cli'nin forklanmış hali değil farklı bir kodlama dili ile sıfırdan türkçe anime izlemek için yazıldı. Bu yüzden eksiklikleri olması doğaldır, ama vlc eklenilebilir, göz önünde bulunduracağım
