### ISSUE TITLE
Repolara eklenebilir

### ISSUE THREAD

**Issue by Aykut551** [DeoDorqnt387/aniwatch-tr#2]
Ana repolar olmasa bile mesela aur gibi yerlere eklenebilir sadece pip'de olmasın

**Comment by DeoDorqnt387** [comment]
AUR'a eklemek zaten uzun süredir aklımda ama ne zaman eklerim bilmiyorum...

**Comment by xeyossr** [comment]
> AUR'a eklemek zaten uzun süredir aklımda ama ne zaman eklerim bilmiyorum...

Hocam sizin için sorun yoksa AUR maintainer olabilirim. Diğer kullanıcılar da böyle AUR'dan indirebilir. Hem başkaları da paket ararken karşılaşıp indirebilir.

**Comment by DeoDorqnt387** [comment]
Gerek yok, eğer bu projeyi V ile sıfırdan yazarsam aura eklemeyi düşünüyorum.

**Comment by DeoDorqnt387** [comment]
> Gerek yok, eğer bu projeyi V ile sıfırdan yazarsam aura eklemeye karar verdim.
