### ISSUE TITLE
Film izlenemiyor

### ISSUE THREAD

**Issue by xeyossr** [DeoDorqnt387/aniwatch-tr#4]
Kullanılan API'den kaynaklı olarak herhangi bir film izlenmiyor. Örnek hata:
```
Error fetching JSON from https://tau-video.xyz/api/video/zSg-CQ39Jrk: Expecting value: line 1 column 1 (char 0)
Error while fetching movie URL: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/kamisaki/.aniwatch-tr/src/main.py", line 5, in <module>
    main()
  File "/home/kamisaki/.aniwatch-tr/src/animeci.py", line 321, in main
    app.srch_anime()
  File "/home/kamisaki/.aniwatch-tr/src/animeci.py", line 211, in srch_anime
    self.handle_menu_option(option)
  File "/home/kamisaki/.aniwatch-tr/src/animeci.py", line 172, in handle_menu_option
    action()
  File "/home/kamisaki/.aniwatch-tr/src/animeci.py", line 49, in play_current_episode
    self.play_episode(self.current_episode_index, quality)
  File "/home/kamisaki/.aniwatch-tr/src/animeci.py", line 281, in play_episode
    open_with_video_player(url)
  File "/home/kamisaki/.aniwatch-tr/src/watch.py", line 14, in open_with_video_player
    subprocess.run(['mpv', '--fullscreen', url], check=True)
  File "/usr/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.12/subprocess.py", line 1885, in _execute_child
    self.pid = _fork_exec(
               ^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Belki filmler için ayrı bir oynatıcıdan veri çekmek daha iyi olabilir.

**Comment by DeoDorqnt387** [comment]
Pip versiyonunda mı, ki sanırsam öyle. Linux'ta ki versiyon, Pip versiyonundan daha ileride ondan dolayı linuxta böyle bir sorun olmaması lazım. Ama eğer Linuxtaki versiyonda bu sorunu yaşıyorsan: Hangi sağlayıcıyı kullanıyorsun AnimeciX mi? yoksa Openanime mi? Tau video sanırsam animeciX'e bağlıydı ancak pek hatırlamıyorum. **Ayrıca eğer pipse denediğin animeyi yazar mısın?** belki sitede anime vardır ancak, animenin bölümü eklenmemiş olabilir. Ayrıca En kısa sürede pip versiyonunuda güncellerim, sanırsam, umarım.

**Comment by xeyossr** [comment]
Date a Live her 2 filmi, Code Geass'in her 3 filmi ve Grisaia no Meikyuu denedim. Hepsinde aynı sorun var (manuel kurulum).

**Comment by DeoDorqnt387** [comment]
> Date a Live her 2 filmi, Code Geass'in her 3 filmi ve Grisaia no Meikyuu denedim. Hepsinde aynı sorun var (manuel kurulum).

Animecix'i biraz inceledim, ve dediğim gibi anime var ama film için hiçbir oynatma tuşu yok.(kör değilsem) Açıkcası mangacix.net ve animecix.net arasındaki farkı anlamaya çalışmam bir yana, sonuç olarak animecix.net sanırsam film değilde anime [dizi]leri oynatmak için tasarlanmış gibi duruyor Eğer film izleme olayı kayıtlı kullanıcılara özel değilse. Bu arada yazdığım kodları birazcık inceledim, (o kadar kötü yazmışım ki allah belamı vermesin) tau-video.xyz bulunamazsa, sibnet kullan diyor ve genellikle animecix.net'te Sibnet tüm animelerde var bu yüzden yeni bir oynatıcı eklemek manasız geldi şu anlık.

**Comment by DeoDorqnt387** [comment]
> Date a Live her 2 filmi, Code Geass'in her 3 filmi ve Grisaia no Meikyuu denedim. Hepsinde aynı sorun var (manuel kurulum).

Tamamdır, çözdüm. Cli'yi sil, kur yaparsan büyük ihtimalle erişebilirsin. Ben de diyorum bu çalışıyordu. Sorun basitmiş. #

**Comment by DeoDorqnt387** [comment]
> > Date a Live her 2 filmi, Code Geass'in her 3 filmi ve Grisaia no Meikyuu denedim. Hepsinde aynı sorun var (manuel kurulum).
> 
> Tamamdır, çözdüm. Cli'yi sil, kur yaparsan büyük ihtimalle erişebilirsin, izleyebilirsim artık filmleri. Ben de diyorum bu çalışıyordu. Sorun basitmiş.

**Comment by xeyossr** [comment]
Evet, sorun çözülmüş duruyor. İlgilendiğiniz için teşekkürler.
